title: Stackbit Fjord Theme
baseURL: /
params:
  footer:
    content: '&copy; All rights reserved.'
    links:
      - new_window: true
        text: Made with Stackbit
        url: 'https://www.stackbit.com'
  header:
    bg_img: ''
    has_nav: true
    has_social: true
    logo_img: ''
    tagline: It's time to fire the stars into the sky!
    title: Stars May Speak
  palette: yellow
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
